GRANT CONNECT ON DATABASE app TO reservcar;

GRANT USAGE ON SCHEMA public TO reservcar;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO reservcar;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO reservcar;

ALTER DEFAULT PRIVILEGES FOR USER app IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO reservcar;

ALTER DEFAULT PRIVILEGES FOR USER app IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO reservcar;
